version: '3.2'

services:
  api:
    build: .
    image: coding-coach:latest
    container_name: 'coding-coach'
    depends_on:
      - mongo
    environment:
      PORT: 3030
      NODE_ENV: production
      MONGO_DB_URI: mongodb://mongo/coding-coach
    ports:
      - 3030:3030 # for development

  mongo:
    image: mongo:latest
    container_name: 'coding-coach-mongodb'
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017 # for development

volumes:
  mongodb: {}
